### ISSUE TITLE
PipeServer/PipeClient examples dont't work if compiled with 64 bit with Delphi community editon 11.3

### ISSUE THREAD

**Issue by groehner** [marsupilami79/DelphiPipes#1]
When I compile the PipeServer and PipeClient sample programs with 32-bit Delphi 11.3, both programs communicate well.
But when I compile them with 64-bit both programs exit after connecting the client to the server.

**Comment by groehner** [comment]
A solution is presented at: 
[https://en.delphipraxis.net/topic/884-named-pipe-failure-multithreading-and-asynchronous-io/?page=2](url)
After exchanging the two wrong longints by LPARAM the PipeServer and PipeClient example programs work correctly in 64-Bit mode.

**Comment by marsupilami79** [comment]
This should be fixed in f115d80. Could you please check and close the issue if it is resolved?

**Comment by groehner** [comment]
It's resolved!
